import { Providers } from "@/components/Providers";
import "./globals.css";
import { Inter } from "next/font/google";
import { SessionProviders } from "@/components/SessionProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Point Of Sales - Ngaos",
    description: "Generated by CV Ngaos Berkah Family",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionProviders>
                    <Providers>{children}</Providers>
                </SessionProviders>
            </body>
        </html>
    );
}
